### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by otatarintseva** [moodlerooms/moodle-coding-standard#1]
Hello,

Could you please update the code with changes from https://github.com/moodlehq/moodle-local_codechecker?
There appeared some changes, for example in https://github.com/moodlehq/moodle-local_codechecker/blob/master/moodle/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php.

**Comment by polothy** [comment]
Sorry, but this package is no longer updated (I updated the description to reflect this).  It was originally created for Moodle Plugin CI project and is still used by the v1 series, but that's no longer maintained.  In v2, it now uses the MoodleHQ project directly.  You can see how it does it by looking [here](https://github.com/blackboard-open-source/moodle-plugin-ci/blob/master/composer.json#L23) and also [this line](https://github.com/blackboard-open-source/moodle-plugin-ci/blob/master/composer.json#L55).

You can read about the feature I'm using at https://getcomposer.org/doc/05-repositories.md
